crystallake/apps/tag/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', AdminTagsList.as_view(), name='admin_tags'),
    path('show/<int:tag_id>/', AdminTagDetail.as_view(), name='admin_show_tag'),
    path('edit/<int:tag_id>/', AdminTagUpdate.as_view(), name='admin_edit_tag'),
    path('create/', AdminTagCreate.as_view(), name='admin_create_tag'),
    path('delete/<int:tag_id>/', AdminDeleteTagView.as_view(), name='admin_delete_tag'),
]

crystallake/crystallake/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings

from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin_django/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('', include('apps.client_profile.additional_urls.register_urls')),
    path('', include('apps.client_profile.additional_urls.reset_password_urls')),
    path('', include('apps.client_profile.additional_urls.auth_urls')),
    path('cart/', include('apps.client_profile.additional_urls.cart_urls')),
    path('profile/', include('apps.client_profile.urls')),
    path('rooms/', include('apps.room.urls')),
    path('services/', include('apps.service.urls')),
    path('services/', include('apps.service.urls')),
    path('admin/', include('apps.worker_profile.urls')),
    path('admin/rooms/', include('apps.room.admin_urls')),
    path('admin/services/', include('apps.service.admin_urls')),
    path('admin/offers/', include('apps.offer.admin_urls')),
    path('admin/tags/', include('apps.tag.urls')),
    path('admin/groups/', include('apps.group.urls')),
    path('admin/clients/', include('apps.client.urls')),
    path('admin/workers/', include('apps.worker.urls')),
    path('admin/orders/', include('apps.order.admin_urls')),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

crystallake/apps/tag/models.py
from django.db import models
from django.shortcuts import reverse


# Create your models here.


class TagQuerySet(models.QuerySet):
    def search(self, **kwargs):
        qs = self
        if kwargs.get('name', ''):
            qs = qs.filter(name__icontains=kwargs['name'])
        if kwargs.get('id', ''):
            qs = qs.filter(pk=kwargs['id'])
        if kwargs.get('sort_by', ''):
            qs = qs.order_by(kwargs['sort_by'])

        return qs


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True, blank=False, null=False, verbose_name='наименование')

    objects = TagQuerySet.as_manager()

    class Meta:
        ordering = ['id']
        verbose_name = 'Тег'

    def __str__(self):
        return self.name

    def get_admin_show_url(self):
        return reverse('admin_show_tag', kwargs={'tag_id': self.pk})

    def get_admin_edit_url(self):
        return reverse('admin_edit_tag', kwargs={'tag_id': self.pk})

    def get_admin_delete_url(self):
        return reverse('admin_delete_tag', kwargs={'tag_id': self.pk})

crystallake/apps/tag/forms.py
from django import forms

from .models import Tag


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name', 'id']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['name'].label = 'Наименование'


class SearchTagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name', 'id']

    id = forms.CharField(max_length=255, label='id', required=False, widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['name'].required = False

crystallake/apps/tag/views.py
from datetime import datetime

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.template.loader import render_to_string
from django.conf import settings


from ..core.utils import SafePaginator, ResponseMessage, RelocateResponseMixin, get_paginator_data, is_ajax
from ..core.forms import ShortSearchForm
from .models import Tag
from .forms import TagForm


# Create your views here.


class AdminTagsList(PermissionRequiredMixin, ListView):
    permission_required = 'tag.view_tag'
    model = Tag
    template_name = 'tag/admin_tags.html'
    context_object_name = 'tags'
    paginate_by = settings.ADMIN_PAGINATE_BY
    paginator_class = SafePaginator

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_page'] = 'tags'
        context['additional_page'] = True
        context['form_tags'] = ShortSearchForm(self.request.GET)
        return context

    def get_queryset(self):
        search_form = ShortSearchForm(self.request.GET)
        tags = Tag.objects.all()

        if search_form.is_valid():
            tags = tags.search(**search_form.cleaned_data)

        return tags


class AdminTagDetail(PermissionRequiredMixin, DetailView):
    permission_required = 'tag.view_tag'
    model = Tag
    template_name = 'tag/admin_show_tag.html'
    context_object_name = 'tag'
    pk_url_kwarg = 'tag_id'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_page'] = 'tags'
        context['additional_page'] = True
        context['delete_link'] = self.object.get_admin_delete_url()
        context['offers'] = self.object.offers.filter(date_deleted=None)    #TODO: МБ ПЕРЕДЕЛАТЬ КАК-ТО БОЛЕЕ КРАСИВО
        return context


class AdminTagUpdate(RelocateResponseMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'tag.update_tag'
    model = Tag
    template_name = 'tag/admin_edit_tag.html'
    context_object_name = 'tag'
    pk_url_kwarg = 'tag_id'
    form_class = TagForm

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_page'] = 'tags'
        context['additional_page'] = True
        return context

    def form_invalid(self, form):
        response_message = ResponseMessage(status=ResponseMessage.STATUSES.ERROR, message=form.errors)
        response = HttpResponse(response_message.get_json(), status=400, content_type='application/json')
        return response

    def form_valid(self, form):
        form.instance.save()
        return self.relocate(form.instance.get_admin_show_url())


class AdminTagCreate(RelocateResponseMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'tag.create_tag'
    model = Tag
    template_name = 'tag/admin_add_tag.html'
    context_object_name = 'tag'
    form_class = TagForm

    def get_success_url(self):
        return self.object.get_admin_show_url()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_page'] = 'tags'
        context['additional_page'] = True
        return context

    def form_invalid(self, form):
        response_message = ResponseMessage(status=ResponseMessage.STATUSES.ERROR, message=form.errors)
        response = HttpResponse(response_message.get_json(), status=400, content_type='application/json')
        return response

    def form_valid(self, form):
        form.instance.save()
        return self.relocate(form.instance.get_admin_show_url())


class AdminDeleteTagView(DeleteView):
    model = Tag
    pk_url_kwarg = 'tag_id'
    success_url = reverse_lazy('admin_tags')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


def find_tags(request, **kwargs):
    tags = Tag.objects.all().search(
        **request.POST.dict()
    )

    tags_page, num_pages = get_paginator_data(tags, request.POST.get('page_number', 1))

    data = {'pages': {
        'pages_count': num_pages,
        'current_page': tags_page.number,
    }, 'items': []}

    if is_ajax(request):
        popup_to_open = request.POST.get('popup_to_open')
        html = render_to_string('core/tags_body.html', {'tags_list': tags_page.object_list, 'popup_to_open': popup_to_open})
        data['items'] = html
    else:
        for tag in tags_page.object_list:
            item = {
                'name': tag.name,
                'id': tag.pk,
                'link': tag.get_admin_show_url()
            }
            data['items'].append(item)

    response_message = ResponseMessage(status=ResponseMessage.STATUSES.OK, data=data)
    return HttpResponse(response_message.get_json(), content_type='application/json', status=200)

crystallake/apps/tag/templates/tag/admin_add_tag.html
{% extends 'core/admin_base.html' %}

{% block breadcrumbs %}
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb link-hover text-dark text-decoration-none fs-5">
            <li class="breadcrumb-item">
                <a href="{% url 'index' %}" class="link-hover text-dark text-decoration-none">
                    Главная
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'admin_tags' %}" class="link-hover text-dark text-decoration-none">
                    Теги
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Добавление тега</li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block content %}


    <form class="shadow p-3 rounded-2 d-flex flex-column gap-4 position-relative default_ajax_edit" method="POST" action=".">

        {% csrf_token %}

        <div>
            <ul id="main_info_errors">
            </ul>
        </div>

        <div class="row">

            <div class="col-12">
                <div class="input-group">
                    <label for="{{ form.name.id_for_label}}" class="input-group-text w-10r" id="basic-addon1">{{ form.name.label }}</label>
                    {{ form.name }}
                </div>
            </div>

            <div class="col-12 mt-4">
                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-lg btn-c_yellow-700">Сохранить</button>
                    <button type="button" class="btn btn-lg btn-c_grey-100" data-goto="{% url 'admin_tags' %}">Отмена</button>
                </div>
            </div>

        </div>

    </form>


{% endblock content %}

crystallake/apps/tag/templates/tag/admin_edit_tag.html
{% extends 'core/admin_base.html' %}

{% block breadcrumbs %}
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb link-hover text-dark text-decoration-none fs-5">
            <li class="breadcrumb-item">
                <a href="{% url 'index' %}" class="link-hover text-dark text-decoration-none">
                    Главная
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'admin_tags' %}" class="link-hover text-dark text-decoration-none">
                    Теги
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ tag.get_admin_edit_url }}" class="link-hover text-dark text-decoration-none">
                    Просмотр тега
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Редактирование тега</li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block content %}


    <form class="shadow p-3 rounded-2 d-flex flex-column gap-4 position-relative default_ajax_edit" method="POST" action=".">

        {% csrf_token %}

         <div>
            <ul id="main_info_errors">
            </ul>
        </div>

        <div class="text-center">
            <span class="fw-bold fs-5">id: </span>
            <span class="fw-bold fs-5">{{ tag.id }}</span>
        </div>

        <div class="row">

            <div class="col-12">
                <div class="input-group">
                    <label for="{{ form.name.id_for_label}}" class="input-group-text w-10r" id="basic-addon1">{{ form.name.label }}</label>
                    {{ form.name }}
                </div>
            </div>

            <div class="col-12 mt-4">
                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-lg btn-c_yellow-700">Сохранить</button>
                    <button type="button" class="btn btn-lg btn-c_grey-100" data-goto="{{ tag.get_admin_show_url }}">Отмена</button>
                </div>
            </div>

        </div>

    </form>


{% endblock content %}

crystallake/apps/tag/templates/tag/admin_show_tag.html
{% extends 'core/admin_base.html' %}

{% block breadcrumbs %}
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb link-hover text-dark text-decoration-none fs-5">
            <li class="breadcrumb-item">
                <a href="{% url 'index' %}" class="link-hover text-dark text-decoration-none">
                    Главная
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'admin_tags' %}" class="link-hover text-dark text-decoration-none">
                    Теги
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Просмотр тега</li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block content %}

    <form class="shadow p-3 rounded-2 d-flex flex-column gap-4 position-relative">


        {% if perms.tag.delete_tag %}
            <i class="fa-regular fa-square-minus text-danger card_icon card_icon__delete" data-bs-toggle="modal" data-bs-target="#delete_modal"></i>
        {% endif %}
        {% if perms.tag.change_tag %}
            <i class="fa-regular fa-pen-to-square card_icon card_icon__edit" data-goto="{{ tag.get_admin_edit_url }}"></i>
        {% endif %}

        <div class="text-center">
            <span class="fw-bold fs-5">id: </span>
            <span class="fw-bold fs-5">{{ tag.id }}</span>
        </div>

        <div class="row">

            <div class="col-12 row">
                <p class="fw-bold col-lg-2  col-5">Наименование:</p>
                <p class="opacity-75 col-lg-10 col-7">{{ tag.name }}</p>
                <hr>
            </div>

        </div>

    </form>

{% endblock content %}

{% block popups %}
    {% include 'core/delete_popup.html' %}
{% endblock popups %}

crystallake/apps/tag/templates/tag/admin_tags.html
{% extends 'core/admin_base.html' %}

{% block breadcrumbs %}
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb link-hover text-dark text-decoration-none fs-5">
            <li class="breadcrumb-item">
                <a href="{% url 'index' %}" class="link-hover text-dark text-decoration-none">
                    Главная
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Теги</li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block content %}

    <form class="shadow p-3 rounded-2 position-relative find_form" action="{% url 'admin_tags' %}" method="GET">

        <i class="fa-regular fa-trash-can text-danger card_icon card_icon__delete clean_btn"></i>

        <div class="row align-items-start justify-content-between py-3">

            <div class="col-12 row justify-content-between mx-auto p-0">

                <div class="col-md-3 col-6">
                    <label for="{{ form_tags.id.id_for_label }}" class="form-label">{{ form_tags.id.label }}</label>
                    {{ form_tags.id }}
                </div>

                <div class="col-md-8 col-12 mt-md-0 mt-3">
                    <label for="{{ form_tags.name.id_for_label }}" class="form-label">{{ form_tags.name.label }}</label>
                    {{ form_tags.name }}
                </div>

                {{ form_tags.sort_by }}
                {{ form_tags.page }}

                <div class="col-12 mt-3">
                    <button class="btn btn-c_yellow-700 w-100 ">Найти</button>
                </div>

            </div>


        </div>

    </form>

    <div class="shadow mt-4 rounded-2 overflow-auto">
    <button class="btn btn-c_grey-100 w-100 rounded-0 py-2 fw-bold" type="button" data-goto="{% url 'admin_create_tag' %}">+ Создать</button>
        <table class="table table-striped table-hover table-bordered">
            <thead data-find-form=".find_form">
            <tr>
                <th scope="col" class="bg-c_yellow-700 text-nowrap col-hover" role="button" data-sortby="id" data-sortby-active>
                    id <i class="fa-solid fa-arrow-down-short-wide text-c_yellow-700"></i>
                </th>
                <th scope="col" class="text-nowrap col-hover" role="button" data-sortby="name">
                    Наименование <i class="fa-solid fa-arrow-down-short-wide text-c_yellow-700"></i>
                </th>
            </tr>
            </thead>
            <tbody>

                {% for tag in page_obj %}

                    <tr>
                        <th scope="row">{{ tag.id }}</th>
                        <td>
                            <a href="{{ tag.get_admin_show_url }}" class="link-hover d-block">{{ tag.name }}</a>
                        </td>
                    </tr>

                {% endfor %}

            </tbody>
        </table>
    </div>

    {% include 'core/pagination.html' %}

{% endblock content %}