crystallake/apps/offer/urls.py
from django.urls import path

from .views import *

# urlpatterns = [
#     path('', RoomsCatalog.as_view(), name='rooms'),
#     path('room/<slug:room_slug>/', RoomDetail.as_view(), name='room'),
# ]

crystallake/crystallake/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings

from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin_django/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('', include('apps.client_profile.additional_urls.register_urls')),
    path('', include('apps.client_profile.additional_urls.reset_password_urls')),
    path('', include('apps.client_profile.additional_urls.auth_urls')),
    path('cart/', include('apps.client_profile.additional_urls.cart_urls')),
    path('profile/', include('apps.client_profile.urls')),
    path('rooms/', include('apps.room.urls')),
    path('services/', include('apps.service.urls')),
    path('services/', include('apps.service.urls')),
    path('admin/', include('apps.worker_profile.urls')),
    path('admin/rooms/', include('apps.room.admin_urls')),
    path('admin/services/', include('apps.service.admin_urls')),
    path('admin/offers/', include('apps.offer.admin_urls')),
    path('admin/tags/', include('apps.tag.urls')),
    path('admin/groups/', include('apps.group.urls')),
    path('admin/clients/', include('apps.client.urls')),
    path('admin/workers/', include('apps.worker.urls')),
    path('admin/orders/', include('apps.order.admin_urls')),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

crystallake/apps/offer/models.py
import datetime
import itertools

from django.db.models import Count, Q
from pytils.translit import slugify

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.apps import apps

from polymorphic.models import PolymorphicModel
from polymorphic.query import PolymorphicQuerySet

from ..tag.models import Tag
from ..core.build_photo_path import build_photo_path
from .price_choises import PRICE_CHOICES
# from ..order.models import Order


# Create your models here.


class OfferQuerySet(PolymorphicQuerySet):
    def search(self, **kwargs):
        qs = self
        if kwargs.get('id', ''):
            qs = qs.filter(id=kwargs['id'])
        if kwargs.get('name', ''):
            qs = qs.filter(name__icontains=kwargs['name'])
        if kwargs.get('price_from', ''):
            qs = qs.filter(default_price__gte=kwargs['price_from'])
        if kwargs.get('price_until', ''):
            qs = qs.filter(default_price__lte=kwargs['price_until'])
        if kwargs.get('sort_by', ''):
            qs = qs.order_by(kwargs['sort_by'])

        return qs


class Offer(PolymorphicModel):

    name = models.CharField(
        verbose_name='наименование',
        max_length=255,
        blank=False,
        null=False
    )
    description = models.TextField(
        verbose_name='описание',
        blank=False,
        null=True
    )
    price_type = models.CharField(
        max_length=50, choices=PRICE_CHOICES,
        blank=False, null=False,
        verbose_name='Цена за',
        default='day',
    )
    default_price = models.DecimalField(
        verbose_name='стандартная цена',
        max_digits=12,
        decimal_places=2,
        blank=False,
        null=False
    )
    prepayment_percent = models.FloatField(
        verbose_name='предоплата',
        blank=False,
        null=False
    )
    refund_percent = models.FloatField(
        verbose_name='возврат',
        blank=False,
        null=False
    )
    main_photo = models.ImageField(
        upload_to=build_photo_path,
        blank=False,
        null=True,
        db_column='main_photo'
    )

    def get_main_photo(self):
        return self.main_photo

    date_create = models.DateTimeField(
        verbose_name='дата создания',
        auto_now_add=True,
        blank=False,
        null=False
    )
    date_deleted = models.DateTimeField(
        verbose_name='дата удаления',
        blank=True,
        null=True
    )
    is_hidden = models.BooleanField(
        verbose_name='скрыто',
        default=False,
        blank=False,
        null=False
    )
    slug = models.SlugField(
        max_length=255,
        unique=True,
        blank=False,
        null=False
    )
    tags = models.ManyToManyField(
        Tag,
        related_name='offers',
        related_query_name='offer',
        blank=True
    )

    objects = OfferQuerySet.as_manager()

    class Meta:
        indexes = [
            models.Index(fields=['date_deleted', 'is_hidden']),
            models.Index(fields=['slug'])
        ]
        ordering = ['date_create']

    def __str__(self):
        return self.name

    def get_info(self):
        return {
            'name': self.name,
            'id': self.pk,
            'default_price': self.pk,
            'is_hidden': self.is_hidden,
        }

    def get_familiar(self):
        have_same_tags = self.__class__.objects.filter(
            date_deleted=None, is_hidden=False, tags__in=self.tags.all()
        ).exclude(pk=self.pk).distinct()
        calced_tags = have_same_tags.annotate(
            count_familiar=Count('tags', filter=Q(tags__in=self.tags.all()))
        ).order_by('-count_familiar')
        if len(calced_tags) < 3:
            return calced_tags.all()
        return calced_tags[0:3]

    def mark_as_deleted(self):
        self.date_deleted = timezone.now()
        self.save()

    def get_add_tag_url(self):
        return reverse('add_tag_to_offer', kwargs={'offer_id': self.pk})

    def get_del_tag_url(self):
        return reverse('del_tag_from_offer', kwargs={'offer_id': self.pk})

    def get_tags_url(self):
        return reverse('get_tags_for_offer', kwargs={'offer_id': self.pk})

    def get_orders_count(self):
        pass

    def _generate_slug(self):
        """
        автоматичекая генерация слага
        """
        value = self.name
        slug_candidate = slug_original = slugify(value)
        for i in itertools.count(1):
            if not Offer.objects.filter(slug=slug_candidate).exists():
                break
            slug_candidate = '{}-{}'.format(slug_original, i)           # если слаг занят, то добавлем цифру в конце

        self.slug = slug_candidate

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_name = self.name                    # сохраняем изначальное имя, на случай, если его изменяет

    def save(self, *args, **kwargs):
        if not self.pk or self.__original_name != self.name:    # если новый объект или сменили имя, то генерируем слаг
            self._generate_slug()
        super().save(*args, **kwargs)

crystallake/apps/offer/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField, RegionalPhoneNumberWidget

from .models import Offer


class OfferForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = [
            'name',
            'description',
            'default_price',
            'prepayment_percent',
            'refund_percent',
            'main_photo',
            'is_hidden'
        ]

    main_photo = forms.ImageField(widget=forms.FileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.short_fields = ['name', 'default_price', 'prepayment_percent', 'refund_percent', 'slug']

        self.number_fields = ['default_price']

        self.fields['is_hidden'].widget.attrs.update({'class': 'form-check-input'})
        self.fields['description'].widget.attrs.update(
            {'class': 'form-control rounded-bottom rounded-0 h-15r flex-grow-1'}
        )
        self.fields['main_photo'].widget.attrs.update(
            {'class': 'upload_img_input d-none', 'accept': 'image/png, image/jpeg, image/jpg'}
        )
        self.fields['main_photo'].required = False

        for field in self.fields:
            if str(field) in self.short_fields:
                self.fields[str(field)].widget.attrs.update({'class': 'form-control'})

            if str(field) in self.number_fields:
                self.fields[str(field)].widget.attrs.update({'min': 1})

    def clean_main_photo(self):
        photo = self.cleaned_data.get("main_photo")

        if not photo:
            raise forms.ValidationError('Главное фото не было выбрано', code='required')

        return photo


class SearchOffersForm(forms.Form):

    SORT_CHOICES = (
        ('default_price', 'возрастанию цен'),
        ('-default_price', 'убыванию цен'),
    )

    date_from = forms.DateField(label='с', required=False, widget=forms.DateInput(attrs={
        'class': 'input_field input_field__date',
        'type': 'date'
    }))
    date_until = forms.DateField(label='до', required=False, widget=forms.DateInput(attrs={
        'class': 'input_field input_field__date',
        'type': 'date'
    }))
    name = forms.CharField(max_length=255, label='Наименование', required=False, widget=forms.TextInput(attrs={
        'class': 'input_field input_field__name'
    }))
    price_from = forms.DecimalField(label='от', required=False, widget=forms.NumberInput(attrs={
        'class': 'input_field input_field__price'
    }))
    price_until = forms.DecimalField(label='до', required=False, widget=forms.NumberInput(attrs={
        'class': 'input_field input_field__price'
    }))
    sort_by = forms.ChoiceField(label='Сортировать по', required=False, widget=forms.Select(attrs={
        'class': 'select_sortby',
    }))

    @classmethod
    def get_sort_choices(cls):      # получаем через метод класса, чтоб брал значение текущего класса, а не
        return cls.SORT_CHOICES     # все время базового

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['sort_by'].choices = self.get_sort_choices()


class SearchOffersAdmin(forms.Form):
    id = forms.IntegerField(label='id', required=False, widget=forms.NumberInput(attrs={
        'class': 'form-control w-auto mw-100'
    }))
    name = forms.CharField(label='Наименование', required=False, widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    dates_from = forms.DateField(label='с', required=False, widget=forms.DateInput(attrs={
        'class': 'form-control w-100 mw-10r rounded-0 flex-grow-0 flex-shrink-1',
        'type': 'date'
    }))
    dates_until = forms.DateField(label='до', required=False, widget=forms.DateInput(attrs={
        'class': 'form-control w-100 mw-10r rounded-0 flex-grow-0 flex-shrink-1 rounded-end',
        'type': 'date'
    }))
    price_from = forms.IntegerField(label='от', required=False, widget=forms.NumberInput(attrs={
        'class': 'form-control w-100 mw-10r rounded-0 flex-grow-0 flex-shrink-1'
    }))
    price_until = forms.IntegerField(label='до', required=False, widget=forms.NumberInput(attrs={
        'class': 'form-control w-100 mw-10r rounded-0 flex-grow-0 flex-shrink-1 rounded-end'
    }))
    sort_by = forms.CharField(required=False, initial='id', widget=forms.TextInput(attrs={
        'class': 'd-none sorting_input',
        'value': 'id'
    }))
    page = forms.IntegerField(required=False, initial=1, widget=forms.NumberInput(attrs={
        'class': 'd-none page_input',
    }))
        

class BookOfferForm(forms.Form):
    first_name = forms.CharField(label='Ваше имя:', required=False, widget=forms.TextInput(attrs={
        'class': 'input_field input_field__name',
    }))
    last_name = forms.CharField(label='Ваша фамилия:', required=False, widget=forms.TextInput(attrs={
        'class': 'input_field input_field__name',
    }))
    phone = PhoneNumberField(
        region='RU',
        label='Номер телефона*:',
        required=True,
        error_messages={
            'invalid': 'Неверный номер номера телефона. Пример: +79999999999 или 8(999)999-99-99'
        },
        widget=RegionalPhoneNumberWidget(attrs={
            'class': 'input_field input_field__phone',
            'placeholder': '+79999999999'
            }
        ))

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if self.user is not None and self.user.is_authenticated:
            self.fields['phone'].widget.attrs['value'] = self.user.phone
            self.fields['phone'].widget.attrs['readonly'] = ''

            self.fields['first_name'].widget.attrs['value'] = self.user.first_name
            self.fields['first_name'].widget.attrs['readonly'] = ''

            self.fields['last_name'].widget.attrs['value'] = self.user.last_name
            self.fields['last_name'].widget.attrs['readonly'] = ''

crystallake/apps/offer/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404

from ..core.utils import SafePaginator, ResponseMessage, get_paginator_data
from ..tag.models import Tag
from .models import Offer


# Create your views here.


def add_tag_to_offer(request, offer_id):
    if request.method == 'POST':
        offer = get_object_or_404(Offer, pk=offer_id)
        tag_id = request.POST.get('elem_id', -1)
        tag = get_object_or_404(Tag, pk=tag_id)
        offer.tags.add(tag)
        offer.save()
        data = {'name': tag.name, 'id': tag.pk, 'link': tag.get_admin_show_url()}
        response_message = ResponseMessage(status=ResponseMessage.STATUSES.OK, data=data)
        return HttpResponse(response_message.get_json(), content_type='application/json', status=200)


def del_tag_from_offer(request, offer_id):
    if request.method == 'POST':
        offer = get_object_or_404(Offer, pk=offer_id)
        tag_id = request.POST.get('elem_id', -1)
        tag = get_object_or_404(Tag, pk=tag_id)
        offer.tags.remove(tag)
        offer.save()
        response_message = ResponseMessage(status=ResponseMessage.STATUSES.OK)
        return HttpResponse(response_message.get_json(), content_type='application/json', status=200)

crystallake/apps/offer/templates/offer/base_admin_create_offer.html
{% extends 'core/admin_base.html' %}

{% block content %}
<form class="shadow p-3 rounded-2 d-flex flex-column gap-4 position-relative main_info_container" id="edit_main_info_form" action="." method="POST" enctype="multipart/form-data">

    {% csrf_token %}


    <div>
        <ul id="main_info_errors">
        </ul>
    </div>

    <div class="row">

        {% block properties %}
        {% endblock properties %}

    </div>

    <div class="row">

        <div class="col-lg-6 col-12">

            <div class="col-12 d-flex flex-column h-100">
                <label class="input-group-text rounded-top rounded-0" for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
                {{ form.description }}
            </div>

        </div>
        <div class="col-lg-6 col-12 mt-lg-0 mt-4">
            <span class="input-group-text rounded-top rounded-0">Главное фото:</span>
            <div id="img_wrapper__temp">
                <img src="" alt="Главное фото" class="img-fluid w-100 img d-none" id="main_photo_holder">

                <button class="btn btn-primary upload_img upload_img_button d-none" type="button">
                    <i class="fa-solid fa-arrow-up-from-bracket"></i>
                    Загрузить фотографию
                </button>

                <button class="btn open_img btn-dark d-none" type="button" data-bs-toggle="modal" data-bs-target="#show_img_modal">
                    <i class="fa-solid fa-up-right-and-down-left-from-center"></i>
                </button>

                <button class="btn btn-lg btn-primary upload_img_button w-100 rounded-0 rounded-bottom" type="button" id="upload_button__temp">
                    <i class="fa-solid fa-arrow-up-from-bracket"></i>
                    Загрузить фотографию
                </button>

                {{ form.main_photo }}

            </div>
        </div>

    </div>

    {% include 'offer/images_accordion_create.html' %}

    <div class="col-12 mt-4">
        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-lg btn-c_yellow-700" id="button_save">Сохранить</button>
            <button type="button" class="btn btn-lg btn-c_grey-100"  data-goto="{{ list_page }}">Назад</button>
        </div>
    </div>

</form>
{% endblock content %}

crystallake/apps/offer/templates/offer/base_admin_edit_offer.html
{% extends 'core/admin_base.html' %}

{% block content %}
    <form class="shadow p-3 rounded-2 d-flex flex-column gap-4 position-relative main_info_container" id="edit_main_info_form" action="{{ offer.get_admin_edit_url }}" method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        <div>
            <ul id="main_info_errors">
            </ul>
        </div>

        <div class="text-center">
            <span class="fw-bold fs-5">id: </span>
            <span class="fw-bold fs-5">{{ offer.id }}</span>
        </div>

        <div class="row">

            {% block properties %}
            {% endblock properties %}

        </div>

        <div class="row">
            <div class="col-lg-6 col-12 ">

                <div class="col-12 d-flex flex-column h-100">
                    <label class="input-group-text rounded-top rounded-0" for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
                    {{ form.description }}
                </div>

            </div>
            <div class="col-lg-6 col-12 mt-lg-0 mt-4">
                <span class="input-group-text rounded-top rounded-0">Главное фото:</span>
                <div class="img_wrapper">
                    <img src="{{ offer.main_photo.url }}" alt="Главное фото" class="img-fluid w-100 img">

                    <button class="btn btn-primary upload_img upload_img_button" type="button" >
                        <i class="fa-solid fa-arrow-up-from-bracket"></i>
                        Загрузить фотографию
                    </button>

                    <button class="btn open_img btn-dark" type="button" data-bs-toggle="modal" data-bs-target="#show_img_modal">
                        <i class="fa-solid fa-up-right-and-down-left-from-center"></i>
                    </button>

                    {{ form.main_photo }}

                </div>
            </div>

        </div>

        {% include 'offer/images_accordion_edit.html' %}

        <div class="col-12 mt-4">
            <div class="d-flex justify-content-between">
                <button type="button" class="btn btn-lg btn-c_yellow-700" id="save_main_btn">Сохранить</button>
                <button type="button" class="btn btn-lg btn-c_grey-100"  data-goto="{{ offer.get_admin_show_url }}">Назад</button>
            </div>
        </div>

    </form>

    {% block additional_info %}
    {% endblock additional_info %}

    <!-- tags -->

    <div class="shadow p-3 d-flex flex-column gap-4 mt-5">

        <div class="text-center">
            <span class="fw-bold fs-5">Теги</span>
        </div>

        <div class="overflow-auto mt-4 rounded-2">

            <button class="btn btn-c_grey-100 w-100 rounded-0 py-2 fw-bold open_search_btn" data-form="#search_tag" type="button" data-bs-toggle="modal" data-bs-target="#add_tag_modal">
                + Добавить
            </button>

{#            <form method="post" action="{{ offer.get_del_tag_url }}" class="delete_additional_form" >#}

{#                {% csrf_token %}#}

                <table class="table table-striped table-hover table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">id тега</th>
                        <th scope="col">Наименование</th>
                        <th scope="col" class="px-3 text-center" type="button">Убрать</th>
                    </tr>
                    </thead>
                    <tbody class="additional_info_tbody" id="tags_list_body">

                        {% for tag in offer.tags.all %}
                            <tr>
                                <th scope="row">{{ tag.id }}</th>
                                <td>
                                    <a href="{{ tag.get_admin_show_url }}" class="link-hover d-block">{{ tag.name }}</a>
                                </td>
                                <td class="p-0 position-relative w-10r">
                                    <form method="post" action="{{ offer.get_del_tag_url }}" class="delete_additional_form" >
                                    {% csrf_token %}
                                        <button class="btn btn-danger w-100 rounded-0 h-100 position-absolute" type="button" data-id="{{ tag.pk }}">Убрать</button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>

{#            </form>#}

        </div>


    </div>

    <!-- end tags -->

{% endblock content %}

{% block popups %}
    {% include 'offer/tags_popup.html' %}
    {% include 'core/show_image_popup.html' %}
    {% block additional_popups %}
    {% endblock additional_popups %}
{% endblock popups %}

crystallake/apps/offer/templates/offer/base_offer.html
{% extends 'core/base.html' %}

{% block header_meta %}
    {% block offer_header_meta %}
    {% endblock offer_header_meta %}
    <script type="application/ld+json">
    [
    {
        "@context": "https://schema.org",
        {% block offer_json_ld %}
        {% endblock offer_json_ld %}
        "name": "{{ offer.name }}",
        "image": "{{ offer.main_photo }}",
        "description": "{{ offer.description }}",
        "offers":
            {
                "@type": "Offer",
                "price": {{ offer.default_price.to_integral_value }},
                "priceCurrency": "RUB"
            }
        {% if familiar %}
        ,
        "isSimilarTo":
            [
                {% for familiar_offer in familiar|slice:":-1" %}
                {
                    "@type": "Product",
                    "name": "{{ familiar_offer.name }}",
                    "image": "{{ familiar_offer.main_photo }}",
                    "description": "{{ familiar_offer.description }}",
                    "url": "{{ familiar_offer.get_absolute_url }}",
                    "offers":
                        {
                            "@type": "Offer",
                            "price": {{ familiar_offer.default_price.to_integral_value }},
                            "priceCurrency": "RUB"
                        }
                },
                {% endfor %}
                {% with familiar|last as last %}
                {
                    "@type": "Product",
                    "name": "{{ last.name }}",
                    "image": "{{ last.main_photo }}",
                    "description": "{{ last.description }}",
                    "url": "{{ last.get_absolute_url }}",
                    "offers":
                        {
                            "@type": "Offer",
                            "price": {{ last.default_price.to_integral_value }},
                            "priceCurrency": "RUB"
                        }
                }
                {% endwith %}
            ]
    {% endif %}
    },
    {% block breadcrumbs_json_ld %}
    {% endblock %}
    ]
    </script>
{% endblock header_meta %}

{% block content %}
<main>

<section class="section">
    <div class="content_container">
        <h1 class="section_title">{{ offer.name }}</h1>

            <div class="breadcrumbs">
                {% block breadcrumbs %}
                {% endblock breadcrumbs %}
            </div>

        <div class="offer">
            <div class="photos_description">

                <div class="photos">
                    <div class="always-slider-required"></div>

                    <img data-number="{{ 0 }}" src="{{ offer.main_photo.url }}" alt="{{ offer.name }} фото" class="photos_img slider_content slider_content__big slider_content__active">

                    {% for photo in offer.photos.all %}
                        <img data-number="{{ photo.order }}" src="{{ photo.path.url }}" alt="{{ offer.name }} фото" class="photos_img slider_content slider_content__big">
                    {% endfor %}

                    <div class="slider">
                    </div>
                </div>

                <div class="description">
                    <div class="description_main">
                        <h3 class="description_title">{{ offer.name }}</h3>
                        <p class="description_text">
                            {{ offer.description|linebreaks }}
                        </p>
                    </div>
                    <div class="description_extra">
                        <div class="description_info">
                            <p class="description_info_item">
{#                                {% if offer.price_type == 'hour' %}#}
                                Цена за {{ offer.get_price_type_display }}:
                                <span class="highlighted">
                                    {{ offer.default_price.to_integral_value }}&#8381;
                                </span>
                            </p>
                        </div>
                        <a href="#offer_book" class="description_button_wrapper">
                            <button class="button__description">Забронировать</button>
                        </a>
                    </div>
                </div>
            </div>

            <div class="info_dates">

                {% block info_dates %}
                {% endblock info_dates %}

            </div>

        </div>


    </div>
</section>

</main>


<section class="section">
<div class="content_container">

    <h2 class="section_title" id="offer_book">Забронировать</h2>


    <form class="book ajax_redirect" method="post" action=".">

        {% csrf_token %}

        <div class="fields">

            <div class="errors_wrapper"></div>

            {% for field in book_form %}
                <div class="field_item">
                     <label class="field_name" for="{{ field.auto_id }}">{{ field.label }}</label>
                    <div class="field_content">
                        {{ field }}
                    </div>
                </div>
            {% endfor %}

            <button type="submit" class="button__book">В корзину</button>

        </div>

    </form>

</div>
</section>

{% if familiar %}
<section class="section">
<div class="content_container">

    <h2 class="section_title">Похожие предложения</h2>

    <div class="recomendations">

        <div class="tablet-slider-required"></div>

        <article class="card_short recomendations_item slider_content slider_content__active" data-goto="{{ familiar.0.get_absolute_url }}">
            <div class="card_inner">
                <img src="{{ familiar.0.main_photo.url }}" alt="{{ familiar.0.name }}" class="card_img">
                <div class="card_info">
                    <p class="card_info_title">{{ familiar.0.name }}</p>
                    <p class="card_info_text">
                        Начиная от:
                        <span class="highlighted">
                            {{ familiar.0.default_price }}&#8381;
                        </span>
                    </p>
                    <button class="card_button card_button__long" data-goto="{{ familiar.0.get_absolute_url }}#offer_book">Забронировать</button>
                </div>
            </div>
        </article>

        {{ offer.get_often_together }}

        {% for familiar_offer in familiar|slice:"1:" %}
            <article class="card_short recomendations_item slider_content" data-goto="{{ familiar_offer.get_absolute_url }}">
                <div class="card_inner">
                    <img src="{{ familiar_offer.main_photo.url }}" alt="{{ familiar_offer.name }}" class="card_img">
                    <div class="card_info">
                        <p class="card_info_title">{{ familiar_offer.name }}</p>
                        <p class="card_info_text">
                            Начиная от:
                            <span class="highlighted">
                                {{ familiar_offer.default_price }}&#8381;
                            </span>
                        </p>
                        <button class="card_button card_button__long" data-goto="{{ familiar_offer.get_absolute_url }}#offer_book">Забронировать</button>
                    </div>
                </div>
            </article>
        {% endfor %}

        <div class="slider slider__hidden">
        </div>

    </div>

</div>
</section>
{% endif %}




{% endblock content %}

{% block popups %}
    {% include 'client_profile/login_popup.html' %}
    <div class="modal_wrapper modal_wrapper__light " id="images_modal">
        <div class="images_popup" id="images_popup">

            <div class="slick_slider">

                <div class="slick_slider_item">
                    <img src="{{ offer.main_photo.url }}">
                </div>
                {% for photo in offer.photos.all %}
                    <div class="slick_slider_item">
                        <img src="{{ photo.path.url }}">
                    </div>
                {% endfor %}

            </div>

            <i class="fa-solid fa-xmark images_close" id="images_close"></i>

        </div>
    </div>
{% endblock popups %}

crystallake/apps/offer/templates/offer/book_general_fields.html
<div class="field_item">
    <label for="{{ book_form.first_name.id_for_label }}" class="field_name">{{ book_form.first_name.label }}</label>
    <div class="field_content">
        {{ book_form.first_name }}
    </div>
</div>

<div class="field_item">
    <label for="{{ book_form.last_name.id_for_label }}" class="field_name">{{ book_form.last_name.label }}</label>
    <div class="field_content">
        {{ book_form.last_name }}
    </div>
</div>

<div class="field_item">
    <label for="{{ book_form.phone.id_for_label }}" class="field_name">{{ book_form.phone.label }}</label>
    <div class="field_content">
        {{ book_form.phone }}
    </div>
</div>


{#<div class="field_item">#}
{#    <label for="input_payment" class="field_name">Оплатить сейчас:</label>#}
{#    <div class="field_content">#}
{#        <select id="input_payment" class="input_field select_field">#}
{#            <option value="1">полностью</option>#}
{#            <option value="2" selected>только предоплату</option>#}
{#        </select>#}
{#    </div>#}
{#</div>#}

<div class="field_item">
    <p class="field_name">К оплате сейчас:</p>
    <div class="field_content">
        <p class="field_info">2.899&#8381;</p>
    </div>
</div>

<div class="field_item">
    <p class="field_name">Суммарная цена:</p>
    <div class="field_content">
        <p class="field_info">12.399&#8381;</p>
    </div>
</div>

<button type="submit" class="button__book">В корзину</button>