crystallake/apps/order/urls.py
from django.urls import path, include

from .views import AdminOrdersList, AdminOrderUpdate, AdminOrderCreate, AdminOrderDetail

urlpatterns = [
    path('', AdminOrdersList.as_view(), name='admin_orders'),
    path('create/', AdminOrderCreate.as_view(), name='admin_create_order'),
    path('create/', include('apps.order.additional_urls.clients_urls')),
    path('show/<int:order_id>/', AdminOrderDetail.as_view(), name='admin_show_order'),
    path('edit/<int:order_id>/', AdminOrderUpdate.as_view(), name='admin_edit_order'),
    path('edit/<int:order_id>/', include('apps.order.additional_urls.rooms_urls')),
    path('edit/<int:order_id>/', include('apps.order.additional_urls.services_urls')),
    path('edit/<int:order_id>/', include('apps.order.additional_urls.purchases_urls')),
    path('edit/<int:order_id>/', include('apps.order.additional_urls.timetables_urls')),
]

crystallake/crystallake/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings

from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin_django/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('', include('apps.client_profile.additional_urls.register_urls')),
    path('', include('apps.client_profile.additional_urls.reset_password_urls')),
    path('', include('apps.client_profile.additional_urls.auth_urls')),
    path('cart/', include('apps.client_profile.additional_urls.cart_urls')),
    path('profile/', include('apps.client_profile.urls')),
    path('rooms/', include('apps.room.urls')),
    path('services/', include('apps.service.urls')),
    path('services/', include('apps.service.urls')),
    path('admin/', include('apps.worker_profile.urls')),
    path('admin/rooms/', include('apps.room.admin_urls')),
    path('admin/services/', include('apps.service.admin_urls')),
    path('admin/offers/', include('apps.offer.admin_urls')),
    path('admin/tags/', include('apps.tag.urls')),
    path('admin/groups/', include('apps.group.urls')),
    path('admin/clients/', include('apps.client.urls')),
    path('admin/workers/', include('apps.worker.urls')),
    path('admin/orders/', include('apps.order.admin_urls')),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

crystallake/apps/order/models.py
from decimal import Decimal

from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.db.models import Q
from polymorphic.models import PolymorphicModel, PolymorphicManager
from django.urls import reverse
from django.utils import timezone

from ..offer.models import Offer
from .status_choises import Status
from ..offer.price_choises import PriceType

# Create your models here.


class OrderQuerySet(models.QuerySet):
    def search(self, **kwargs):
        qs = self
        if kwargs.get('id', ''):
            qs = qs.filter(pk=kwargs['id'])
        if kwargs.get('status', ''):
            status = kwargs['status']
            if status == Status.finished.name:
                qs = qs.filter(~Q(date_finished=None))
            if status == Status.canceled.name:
                qs = qs.filter(~Q(date_canceled=None))
            if status == Status.process.name:
                qs = qs.filter(date_finished=None, date_canceled=None)
        if kwargs.get('client_id', ''):
            qs = qs.filter(client__id=kwargs['client_id'])

        if kwargs.get('sort_by', ''):
            qs = qs.order_by(kwargs['sort_by'])

        return qs


class Order(models.Model):
    client = models.ForeignKey("user.CustomUser", on_delete=models.PROTECT, verbose_name='Клиент')
    comment = models.TextField(verbose_name="комментарий к заказу", blank=True, null=True)
    paid = models.DecimalField(max_digits=12, decimal_places=2, default=0, verbose_name='Оплачено')     # сколько заплатили
    refunded = models.DecimalField(max_digits=12, decimal_places=2, default=0, verbose_name='Возвращено')
    date_create = models.DateTimeField(verbose_name="дата создания", auto_now_add=True)
    date_full_prepayment = models.DateTimeField(verbose_name="дата полной предоплаты", blank=True, null=True)
    date_full_paid = models.DateTimeField(verbose_name="дата полной оплаты", blank=True, null=True)
    date_finished = models.DateTimeField(verbose_name="дата завершения", blank=True, null=True)
    date_canceled = models.DateTimeField(verbose_name="дата отмены", blank=True, null=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.pk:
            self.__original_paid,  self.__original_price = self.paid,  self.price
        else:
            self.__original_paid, self.__original_price = 0, 0

    def save(self, *args, **kwargs):
        if self.pk and (self.__original_paid != self.paid or self.__original_price != self.price):
            self.check_payment()
        super().save(*args, **kwargs)

    def check_payment(self):
        if self.paid >= self.prepayment:
            self.purchases.filter(is_canceled=False).update(is_prepayment_paid=True)
            if self.date_full_prepayment is None:
                self.date_full_prepayment = timezone.now()

        if self.paid >= self.price:
            self.purchases.filter(is_canceled=False).update(is_paid=True)
            if self.date_full_paid is None:
                self.date_full_paid = timezone.now()

        if self.paid < self.prepayment and self.date_full_prepayment is not None:
            self.date_full_prepayment = None
            if self.paid < self.__original_paid:
                self.purchases.filter(is_canceled=False).update(is_prepayment_paid=False)

        if self.paid < self.price and self.date_full_paid is not None:
            self.date_full_paid = None
            if self.paid < self.__original_paid:
                self.purchases.filter(is_canceled=False).update(is_paid=False)

    def mark_as_prepayment_paid(self):
        self.paid = self.prepayment
        self.save()

    def mark_as_fully_paid(self):
        self.paid = self.price
        self.save()

    def mark_as_refund_made(self):
        for purchase in self.purchases.filter(is_canceled=True, is_refund_made=False):
            purchase.is_refund_made = True
            purchase.save()
        refund_made = self.left_to_refund
        self.paid -= refund_made
        self.refunded += refund_made
        self.save()

    def mark_as_canceled(self):
        if self.is_cancelable():
            self.date_canceled = timezone.now()
            self.date_finished = None
            self.save()
            for purchase in self.purchases.filter(is_canceled=False, is_paid=False):
                purchase.is_canceled = True
                purchase.save()

    def mark_as_finished(self):
        self.date_canceled = None
        self.date_finished = timezone.now()
        if self.paid < self.price:
            self.paid = self.price
        self.save()
        for purchase in self.purchases.filter(is_canceled=False, is_paid=False):
            purchase.is_paid = True
            purchase.save()

    def mark_as_in_process(self):
        self.date_canceled = None
        self.date_finished = None
        self.save()

    def is_editable(self):
        if self.status == Status.finished.value or self.status == Status.canceled.value:
            return False
        return True

    def is_cancelable(self):
        if self.date_canceled is not None:
            return False
        return True

    @property
    def price(self):
        price = 0
        if not self.pk:
            return 0
        for purchase in self.purchases.all():
            if purchase.is_canceled and purchase.is_paid:
                price += purchase.price - purchase.refund
            elif purchase.is_canceled and not purchase.is_paid:
                price += purchase.prepayment
            elif not purchase.is_canceled:
                price += purchase.price

        return price

    @property
    def prepayment(self):
        prepayment = 0
        if not self.pk:
            return 0
        for purchase in self.purchases.filter(is_canceled=False):
            prepayment += purchase.prepayment
        return prepayment

    @property
    def left_to_refund(self):
        left_to_refund = self.paid - self.price
        if left_to_refund > 0:
            return left_to_refund
        return 0

    @property
    def left_to_pay(self):
        left_to_pay = self.price - self.paid
        if left_to_pay > 0:
            return left_to_pay
        return 0

    @property
    def status(self):
        if self.date_finished is not None:
            return Status.finished.value
        if self.date_canceled is not None:
            return Status.canceled.value
        return Status.process.value

    @property
    def payment_status(self):
        if self.date_full_paid is not None:
            return 'Полностью оплачен'
        if self.date_full_prepayment is not None:
            return 'Внесена предоплата'
        return 'Ожидает предоплату'

    @property
    def main_offer(self):
        if self.get_active_purchases().count() > 0:
            main_purchase = self.purchases.filter(is_canceled=False).order_by('-price').first()
            return main_purchase.offer
        main_purchase = self.purchases.order_by('-price').first()
        if main_purchase is not None:
            return main_purchase.offer

    @property
    def name(self):
        purchases_count = self.purchases.count()
        if purchases_count > 1:
            return f'{self.main_offer.name} и еще {purchases_count - 1} покупок'
        if self.main_offer is not None:
            return self.main_offer.name
        return f'Заказ от {self.date_create.date()}'

    @property
    def is_cart(self):
        if self.paid == 0 and self.refunded == 0 and self.date_canceled is None and self.date_finished is None:
            return True
        return False

    def get_active_purchases(self):
        return self.purchases.filter(is_canceled=False)

    def get_admin_edit_url(self):
        return reverse('admin_edit_order', kwargs={'order_id': self.pk})

    def get_admin_show_url(self):
        return reverse('admin_show_order', kwargs={'order_id': self.pk})

    def get_create_room_purchase_url(self):
        return reverse('create_room_purchase', kwargs={'order_id': self.pk})

    def get_create_service_purchase_url(self):
        return reverse('create_service_purchase', kwargs={'order_id': self.pk})

    def get_client_manage_url(self):
        return reverse('client_manage_order', kwargs={'order_id': self.pk})

    def get_client_cancel_url(self):
        return reverse('client_cancel_order', kwargs={'order_id': self.pk})

    def get_client_pay_url(self):
        return reverse('client_pay', kwargs={'order_id': self.pk})

    def get_client_history_url(self):
        return reverse('history_item', kwargs={'order_id': self.pk})

    class Meta:
        indexes = [
            models.Index(fields=['paid', 'refunded', 'date_create'])
        ]
        ordering = ['-date_create']

    objects = OrderQuerySet.as_manager()


class PurchaseManager(PolymorphicManager):
    def update_order_decorator(bulk_func):
        """
        ДЕКОРАТОР ДЛЯ ОБНОВЛЕНИЯ ЗАКАЗА ПОСЛЕ ДОБАВЛЕНИЯ ЭЛЕМЕНТОВ
        """
        from functools import wraps
        @wraps(bulk_func)
        def wrapper(*args, **kwargs):
            purchases = bulk_func(*args, **kwargs)
            if len(purchases) > 0:
                order = purchases[0].order
                order.save()

        return wrapper

    @update_order_decorator
    def bulk_create(self, purchases, **kwargs):
        for purchase in purchases:
            purchase.clean()
            purchase.price = purchase.calc_price()
            purchase.prepayment = purchase.calc_prepayment()
            purchase.refund = purchase.calc_refund()
            if not purchase.is_canceled:
                purchase.is_paid = False
                purchase.is_prepayment_paid = False
        return super(PurchaseManager, self).bulk_create(purchases, **kwargs)


class Purchase(PolymorphicModel):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="purchases")

crystallake/apps/order/forms.py
from django import forms

from .models import Order, Purchase, PurchaseCountable
from .status_choises import get_status_by_name, STATUS_CHOICES, STATUS_CHOICES_SEARCH


class CreateOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['comment']

    client_name = forms.CharField(label='Клиент', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'readonly': ''
    }))
    client_id = forms.IntegerField(widget=forms.HiddenInput(attrs={
        'class': 'd-none'
    }))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['comment'].widget.attrs.update({'class': 'form-control rounded-bottom rounded-0 h-10r'})
        self.fields['comment'].label = 'Комментарий'


class EditOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['comment', 'paid']

    refund_made = forms.BooleanField(label='Средства возвращены', required=False, widget=forms.CheckboxInput(attrs={
        'class': 'btn-check'
    }))
    status = forms.ChoiceField(choices=STATUS_CHOICES, widget=forms.RadioSelect(attrs={
        'class': 'btn-check'
    }))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['status'].initial = get_status_by_name(self.instance.status)

        if not self.instance.is_editable():
            self.fields['comment'].disabled = True
            self.fields['paid'].disabled = True

        if self.instance.left_to_refund == 0:
            self.fields['refund_made'].disabled = True

        self.fields['comment'].widget.attrs.update({'class': 'form-control rounded-bottom rounded-0 h-10r'})
        self.fields['paid'].widget.attrs.update({'class': 'form-control rounded-bottom rounded-0'})


class SearchOrdersAdmin(forms.Form):
    id = forms.IntegerField(label='id', required=False, widget=forms.NumberInput(attrs={
        'class': 'form-control'
    }))
    status = forms.ChoiceField(label='Статус заказа', choices=STATUS_CHOICES_SEARCH, required=False, widget=forms.Select(attrs={
        'class': 'form-select w-100 mw-10r flex-grow-0 flex-shrink-1'
    }))
    client_id = forms.IntegerField(required=False, widget=forms.HiddenInput(attrs={
        'class': 'd-none'
    }))
    client_name = forms.CharField(label='Клиент', required=False, widget=forms.TextInput(attrs={
        'class': 'form-control rounded-0 rounded-start',
        'readonly': ''
    }))
    sort_by = forms.CharField(required=False, initial='id', widget=forms.TextInput(attrs={
        'class': 'd-none sorting_input',
        'value': 'id'
    }))
    page = forms.IntegerField(required=False, initial=1, widget=forms.NumberInput(attrs={
        'class': 'd-none page_input',
    }))


class PurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = []

    purchase_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)


class RoomPurchaseForm(PurchaseForm):
    class Meta(PurchaseForm.Meta):
        fields = [*PurchaseForm.Meta.fields, 'start', 'end']
        widgets = {
            'start': forms.DateInput(attrs={
                'class': 'form-control',
                'type': 'date'
            }),
            'end': forms.DateInput(attrs={
                'class': 'form-control',
                'type': 'date'
            }),
        }

    room_id = forms.IntegerField(required=False, widget=forms.HiddenInput(attrs={
        'class': 'd-none'
    }))

    multiple_rooms_acceptable = forms.BooleanField(
        label='Разрешить подбор нескольких комнат',
        required=False,
        widget=forms.CheckboxInput(attrs={
            'class': 'btn-check',
            'type': 'checkbox',
        })
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['start'].label = 'Заселение'
        self.fields['end'].label = 'Выселение'


class ServicePurchaseForm(PurchaseForm):
    class Meta(PurchaseForm.Meta):
        model = PurchaseCountable
        fields = [*PurchaseForm.Meta.fields, 'quantity']

    service_id = forms.IntegerField(required=False, widget=forms.HiddenInput(attrs={
        'class': 'd-none'
    }))
    day = forms.DateField(label='Дата', required=False, widget=forms.DateInput(attrs={
        'class': 'form-control',
        'type': 'date'
    }))
    time_start = forms.TimeField(label='Время начала', required=False, widget=forms.TimeInput(attrs={
        'class': 'form-control',
        'type': 'time'
    }))
    time_end = forms.TimeField(label='Время конца', required=False, widget=forms.TimeInput(attrs={
        'class': 'form-control',
        'type': 'time'
    }))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['quantity'].widget.attrs.update({'class': 'form-control'})
        self.fields['quantity'].initial = 1
        self.fields['quantity'].label = 'Количество'

crystallake/apps/order/templates/order/admin_create_order.html
{% extends 'core/admin_base.html' %}

{% block breadcrumbs %}
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb link-hover text-dark text-decoration-none fs-5">
            <li class="breadcrumb-item">
                <a href="{% url 'index' %}" class="link-hover text-dark text-decoration-none">
                    Главная
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'admin_orders' %}" class="link-hover text-dark text-decoration-none">
                    Заказы
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Добавление заказа</li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block content %}


    <form class="shadow p-3 rounded-2 d-flex flex-column gap-4 position-relative default_ajax_edit" method="POST" action=".">

        {% csrf_token %}

        <div>
            <ul id="main_info_errors">
            </ul>
        </div>

        <div class="row justify-content-between">

            <div class="col-lg-6 col-12">

                <div class="w-100">
                    <div class="input-group d-flex flex-nowrap">
                        <label for="{{ form.client_name.id_for_label }}" class="input-group-text w-7r">{{ form.client_name.label }}</label>
                        <div class="d-flex flex-grow-1">
                            {{ form.client_name }}
                            {{ form.client_id }}
                            <button class="btn btn-primary w-5r rounded-0 rounded-end open_search_btn" data-form="#search_clients"  type="button" data-bs-toggle="modal" data-bs-target="#pick_client_modal">
                                <i class="fa-solid fa-magnifying-glass"></i>
                            </button>
                        </div>

                    </div>
                </div>

            </div>

            <div class="col-lg-6 col-12 mt-lg-0 mt-4">
                <label class="input-group-text rounded-top rounded-0" for="{{ form.comment.id_for_label }}">{{ form.comment.label }}</label>
                {{ form.comment }}
            </div>

            <div class="col-12 mt-4">
                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-lg btn-c_yellow-700">Продолжить</button>
                    <button type="button" class="btn btn-lg btn-c_grey-100" data-goto="{% url 'admin_workers' %}">Отмена</button>
                </div>
            </div>

        </div>

    </form>


{% endblock content %}

{% block popups %}
    {% include 'order/clients_popup.html' %}
{% endblock popups %}

crystallake/apps/order/templates/order/admin_orders.html
{% extends 'core/admin_base.html' %}

{% block breadcrumbs %}
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb link-hover text-dark text-decoration-none fs-5">
            <li class="breadcrumb-item">
                <a href="{% url 'index' %}" class="link-hover text-dark text-decoration-none">
                    Главная
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Заказы</li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block content %}


    <form class="shadow p-3 rounded-2 position-relative find_form" action="{% url 'admin_orders' %}" method="GET">

        <i class="fa-regular fa-trash-can text-danger card_icon card_icon__delete clean_btn"></i>

       <div class="row align-items-start justify-content-between">

            <div class="col-12 row mx-auto p-0">

                <div class="col-12 row mx-auto p-0">

                    <div class="col-lg-2 col-md-3 col-6">
                        <label for="{{ form.id.id_for_label }}" class="form-label text-nowrap">{{ form.id.label }}:</label>
                        {{ form.id }}
                    </div>

                    <div class="col-lg-2 col-md-3 col-6">
                        <label for="{{ form.status.id_for_label }}" class="form-label">{{ form.status.label }}</label>
                        {{ form.status }}
                    </div>

                    <div class="col-lg-8 col-md-6 col-12 mt-md-0 mt-3">
                        <label for="{{ form.client_name.id_for_label }}" class="form-label">{{ form.client_name.label }}</label>
                        <div class="d-flex">
                            {{ form.client_name }}
                            {{ form.client_id }}
                            <button class="btn btn-primary w-5r rounded-0 rounded-end open_search_btn" data-form="#search_clients"  type="button" data-bs-toggle="modal" data-bs-target="#pick_client_modal">
                                <i class="fa-solid fa-magnifying-glass"></i>
                            </button>
                        </div>
                    </div>

                    {{ form.sort_by }}
                    {{ form.page }}

                    <div class="col-12 mt-3">
                        <button class="btn btn-c_yellow-700 w-100 ">Найти</button>
                    </div>

                </div>

            </div>
       </div>

    </form>

    <div class="shadow mt-4 rounded-2 overflow-auto">
     <button class="btn btn-c_grey-100 w-100 rounded-0 py-2 fw-bold" type="button" data-goto="{% url 'admin_create_order' %}">+ Создать</button>
        <table class="table table-striped table-hover table-bordered">
            <thead data-find-form=".find_form">
            <tr>
                <th scope="col" class="bg-c_yellow-700 text-nowrap col-hover" role="button" data-sortby="id" data-sortby-active>
                    id <i class="fa-solid fa-arrow-down-short-wide text-c_yellow-700"></i>
                </th>
                <th scope="col" class="text-nowrap">
                    Наименование
                </th>
                <th scope="col" class="text-nowrap col-hover" role="button"  data-sortby="client__name">
                    Клиент <i class="fa-solid fa-arrow-down-short-wide text-c_yellow-700"></i>
                </th>
                <th scope="col" class="text-nowrap">
                    Статус заказ
                </th>
                <th scope="col" class="text-nowrap">
                    Статус оплаты
                </th>
                <th scope="col" class="text-nowrap">
                    Цена
                </th>
            </tr>
            </thead>
            <tbody>

                {% for order in page_obj %}

                    <tr>
                        <th scope="row">{{ order.pk }}</th>
                        <td>
                            <a href="{{ order.get_admin_show_url }}" class="link-hover d-block">{{ order.name }}</a>
                        </td>
                        <td>
                            <a href="{{ order.client.get_admin_show_url }}" class="link-hover d-block">{{ order.client.full_name }}</a>
                        </td>
                        <td>{{ order.status }}</td>
                        <td>{{ order.payment_status }}</td>
                        <td>{{ order.price }}&#8381;</td>
                    </tr>

                {% endfor %}

            </tbody>
        </table>
    </div>

    {% include 'core/pagination.html' %}

{% endblock content %}
{% block popups %}
    {% include 'order/clients_popup.html' %}
{% endblock popups %}

crystallake/apps/order/templates/order/admin_show_order.html
{% extends 'core/admin_base.html' %}

{% block breadcrumbs %}
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb link-hover text-dark text-decoration-none fs-5">
            <li class="breadcrumb-item">
                <a href="{% url 'index' %}" class="link-hover text-dark text-decoration-none">
                    Главная
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'admin_orders' %}" class="link-hover text-dark text-decoration-none">
                    Заказы
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Просмотр заказа</li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block content %}

    <div class="shadow p-3 rounded-2 d-flex flex-column gap-4 position-relative">


        {% if perms.order.change_order %}
            <i class="fa-regular fa-pen-to-square card_icon card_icon__edit" data-goto="{{ order.get_admin_edit_url }}"></i>
        {% endif %}

        <div class="text-center">
            <span class="fw-bold fs-5">id: </span>
            <span class="fw-bold fs-5">{{ order.pk }}</span>
        </div>

        <div class="row">

            <div class="col-lg-6 col-12 row">
                <p class="fw-bold col-5">Название:</p>
                <p class="opacity-75 col-7">{{ order.name }}</p>
                <hr>
            </div>

            <div class="col-lg-6 col-12 mt-lg-0 mt-2 row">
                <p class="fw-bold col-5">Клиент:</p>
                <a class="opacity-75 col-7 link-hover" href="{{ order.client.get_admin_show_url }}">{{ order.client.full_name }}</a>
                <hr>
            </div>

            <div class="col-lg-6 col-12 mt-2 row">
                <p class="fw-bold col-5">Статус оплаты:</p>
                <p class="opacity-75 col-7">{{ order.payment_status }}</p>
                <hr>
            </div>

            <div class="col-lg-6 col-12 mt-2 row">
                <p class="fw-bold col-5">Статус заказа:</p>
                <p class="opacity-75 col-7">{{ order.status }}</p>
                <hr>
            </div>

            <div class="col-lg-6 col-12 mt-2 row">
                <p class="fw-bold col-5">Цена:</p>
                <p class="opacity-75 col-7">{{ order.price }}</p>
                <hr>
            </div>

            <div class="col-lg-6 col-12 mt-2 row">
                <p class="fw-bold col-5">Предоплата:</p>
                <p class="opacity-75 col-7">{{ order.prepayment }}</p>
                <hr>
            </div>

            <div class="col-lg-6 col-12 mt-2 row">
                <p class="fw-bold col-5">Оплачено:</p>
                <p class="opacity-75 col-7">{{ order.paid }}</p>
                <hr>
            </div>

            <div class="col-lg-6 col-12 mt-2 row">
                <p class="fw-bold col-5">Осталось оплатить:</p>
                <p class="opacity-75 col-7">{{ order.left_to_pay }}</p>
                <hr>
            </div>

            <div class="col-lg-6 col-12 mt-2 row">
                <p class="fw-bold col-5">К возврату:</p>
                <p class="opacity-75 col-7">{{ order.left_to_refund }}</p>
                <hr>
            </div>

            <div class="col-lg-6 col-12 mt-2 row">
                <p class="fw-bold col-5">Возвращено:</p>
                <p class="opacity-75 col-7">{{ order.refunded }}</p>
                <hr>
            </div>

            <div class="col-12 mt-2 row">
                <p class="fw-bold col-12">Комментарий к заказу:</p>
                <p class="opacity-75 col-12">{{ order.comment|linebreaks }}</p>
                <hr>
            </div>

        </div>

    </div>

    <!-- purchases -->

    <div class="shadow p-3 d-flex flex-column gap-4 mt-5">

        <div class="text-center">
            <span class="fw-bold fs-5">Покупки в заказе</span>
        </div>

        <div class="overflow-auto mt-4 rounded-2">

                <table class="table table-striped table-hover table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">Наименование</th>
                        <th scope="col">Начало</th>
                        <th scope="col">Конец</th>
                        <th scope="col">Количество</th>
                        <th scope="col">Стоимость</th>
                    </tr>
                    </thead>
                    <tbody class="additional_info_tbody" id="tags_list_body">

                        {% for purchase in order.purchases.all %}
                            {% if purchase.is_canceled %}
                                <tr class="opacity-50">
                            {% else %}
                                <tr>
                            {% endif %}

                                <th scope="row">{{ purchase.offer.pk }}</th>
                                <td>
                                    <a href="{{ purchase.offer.get_admin_show_url }}" class="link-hover d-block">{{ purchase.offer.name }}</a>
                                </td>
                                <td>
                                    {{ purchase.start }}
                                </td>
                                <td>
                                    {{ purchase.end }}
                                </td>
                                <td>
                                    {% if purchase.quantity %}
                                        {{ purchase.quantity }}
                                    {% else %}
                                        Нет
                                    {% endif %}
                                </td>
                                <td>
                                    {{ purchase.price }}
                                </td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>


        </div>


    </div>
    <!-- end purchases -->

{% endblock content %}

{% block popups %}
{% endblock popups %}

crystallake/apps/order/templates/order/services_body.html
{% for service in services_list %}
    <tr>
        <th scope="row">{{ service.id }}</th>
        <td>
            <a class="link-hover" href="{{ service.get_admin_show_url }}">{{ service.name }}</a>
        </td>
        <td>{{ service.default_price }}</td>
        <td class="p-0 position-relative w-10r">
            <button data-id="{{ service.id }}" class="btn btn-primary w-100 rounded-0 h-100 position-absolute" data-bs-dismiss="modal" type="button">
                Выбрать
            </button>
        </td>
    </tr>
{% endfor %}